dist: trusty
sudo: false
services:
    - postgresql
addons:
    postgresql: "9.6"
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install pipenv
    - pipenv lock
    - pipenv install --dev
before_script:
    - psql --version
    - psql -U postgres -c 'SELECT version();'
    - psql -c 'create database serveradmin owner travis;' -U postgres
    - echo "SECRET_KEY = 'TEST'" > serveradmin/local_settings.py
    - echo "LOGGING = {}" >> serveradmin/local_settings.py
    - python -m serveradmin migrate
script:
    # This will use Python's standard unit test discovery feature.
    - python -m unittest discover adminapi -v
    - python -Wall -m serveradmin test --noinput --parallel
    # Build sphinx docs, error on warning
    - cd docs
    - SPHINXOPTS='-W' make html
