version: "3.9"

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ".docker/db/postgres.conf:/etc/postgresql/postgres.conf:ro"
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    command: "-c config_file=/etc/postgresql/postgres.conf"

  web:
    build: .docker/web
    volumes:
      - ".:/code"
    ports:
      - "127.0.0.1:8000:8000"
    command: "./run.sh"
    depends_on:
      - db
      - pdns-db

  pdns-db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      - POSTGRES_DB=${POSTGRES_PDNS_DB}
      - POSTGRES_USER=${POSTGRES_PDNS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PDNS_PASSWORD}
    volumes:
      - ".docker/pdns-db/postgres.conf:/etc/postgresql/postgres.conf:ro"
    ports:
      - "127.0.0.1:6432:5432"
    command: "-c config_file=/etc/postgresql/postgres.conf"

  pdns-auth:
    build: .docker/pdns-auth
    environment:
      - GPGSQL_HOST=${POSTGRES_PDNS_HOST}
      - GPGSQL_PORT=5432
      - GPGSQL_DBNAME=${POSTGRES_PDNS_DB}
      - GPGSQL_USER=${POSTGRES_PDNS_USER}
      - GPGSQL_PASSWORD=${POSTGRES_PDNS_PASSWORD}
    ports:
      - "127.0.0.1:1053:53"
      - "127.0.0.1:1053:53/udp"
    depends_on:
      - pdns-db

volumes:
  postgres-data:
