[package]
name = "adminapi"
version = "0.1.0"
edition = "2021"
description = "The ServerAdmin API available in Rust"

[dependencies]
anyhow = "1.0.82"
hmac = "0.12.1"
log = "0.4.21"
reqwest = { version = "0.12.3", features = ["json"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
sha1 = "0.10.6"

[dev-dependencies]
env_logger = "0.11.3"
tokio = { version = "1.37.0", features = ["full"] }
